---
title: "fRegress for Fei Update"
author: "Rohan Mishra"
date: "6/27/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE)
library(fda)
library(tidyverse)
library(gridExtra)
source("/mnt/fda_CI.R")

```

We have __ datasets, with different variations in starting Cooling Temperature and Inlet Temperature.


```{r load data and create list}


### load the data
data <- "/mnt/DATA/Tin & Tc Variation/fiveRunsallCombos.csv" %>% read_csv()
#datatemp <- data %>% filter(time %in% c(1:50))

## split the data
data_sp <- data %>% 
  split(f=data$Replicate) 
rep <- names(data_sp)


meanTc_Tin <- lapply(data_sp, function(i) {
  i %>% 
    summarise(Tin_group = round(mean(Temp_inlet)) %>% as.character(),Tc_group = round(mean(coolingTemp)) %>% as.character())
  }) %>% 
  bind_rows() %>%
 mutate(Replicate = rep)
# meanTc_Tin$Replicate <- as.integer(meanTc_Tin$Replicate)


data2 <- inner_join(data,meanTc_Tin, by = "Replicate")
#data2$factor <- paste(data2$Replicate, data2$meanTin,data2$meanTc, sep = "_")


#### PLOTS FOR SLIDE #3 #####
meanTc_conA_5_sec <- data2 %>% 
  filter(time <5) %>%
  #filter()
  ggplot(aes(x=time, y = concentrationA, color = Tc_group, group = as.character(Replicate))) + 
  geom_line() + ggtitle("Output of Ca over First 5 seconds by Mean Tc")
  
meanTc_temp_5sec <-  data2 %>% 
  filter(time <5) %>%
  ggplot(aes(x=time, y = Temp, color = Tc_group, group = as.character(Replicate))) + 
  geom_line() + ggtitle("Output of Reactor Temperature over First 5 seconds by Mean Tc")

grid.arrange(meanTc_conA_5_sec, meanTc_temp_5sec)  
######


#### PLOTS FOR SLIDE #4 #####
only_275Tc <- data2 %>% 
  filter(time < 2) %>%  
  filter(Tin_group == 275) %>%
  ggplot(aes(x=time, y=concentrationA, color = Tin_group, group = Replicate)) + 
  geom_line() +
  ggtitle("Concentration of A for Tc = 275K")

only_275_Tc <- data2 %>% 
  filter(time < 2) %>%  
  filter(meanTc == 275) %>%
  ggplot(aes(x=time, y=Temp, color = Tin_group, group = Replicate)) + 
  geom_line() +
  ggtitle("Reactor Temperature for Tc = 275K")

grid.arrange(only_275Tc, only_275_Tc)
#######



#### correlation summaries ####
data2 %>% 
  group_by(Tin_group) %>% 
  summarise(cor=cor(concentrationA, Temp)) %>%
  arrange(cor)

data2 %>%
  group_by(Tc_group) %>%
  summarise(cor=cor(concentrationA, Temp)) %>%
  arrange(cor)
####

```

change replicate to starting cooling temp & inlet temp

```{r fda}


data_con <- lapply(data_sp, function(i)
  i %>%
    select(time, concentrationA)) %>%
  reduce(inner_join, by = "time")
names(data_con) <- c("time", rep)

data_temp <- lapply(data_sp, function(i)
  i %>%
    select(time, Temp)) %>%
  reduce(inner_join, by = "time")
names(data_temp) <- c("time", rep)



basis <- create.bspline.basis(rangeval = c(0,5001), nbasis = 50)
basis_small <- create.bspline.basis(rangeval = c(0,21), nbasis = 10)

data_con_fd <- smooth.basis(argvals = 1:5001,data_con[,-1] %>% as.matrix(),basis)$fd

data_temp_fd <- smooth.basis(argvals = 1:5001,data_temp[,-1] %>% as.matrix(),basis)$fd



data_con_fd_partial <- smooth.basis(argvals = 1:21,data_con[1:21,-1] %>% as.matrix(),basis_small)$fd

data_temp_fd_partial <- smooth.basis(argvals = 1:21,data_temp[1:21,-1] %>% as.matrix(),basis_small)$fd


Tin <- meanTc_Tin$Tin_group %>% as.numeric()
Tc <- meanTc_Tin$Tc_group %>% as.numeric()
TinTC <- Tin * Tc


fTin <- fRegress(data_con_fd ~ Tin )
fTc <- fRegress(data_con_fd ~ Tc)

fBoth <- fRegress(data_con_fd ~ Tin + Tc)



fBoth$betaestlist


```

be able to generate datasets with a for loop in python <CHECK>
be able to construct a story 
run pca on concentrationA & temp <CHECK> -- doesn't show much, not worth including

