---
title: "MDS Rank"
author: "Rohan Mishra"
date: "10/10/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

rm(list=ls())
library(lsa)
library(qcc)
library(fda)
library(HMPTrees)
library(tidyverse)
library(gridExtra)
library(grid)
options(scipen=9999)
options(max.print = 10000000) 
z_trans <- function(r) 0.5*(log(1+r, base = exp(1))-log(1-r, base = exp(1))) 
knitr::opts_chunk$set(echo = TRUE)

```

```{r Last Week}

#dataFei <- read.csv("/mnt/DATA/Fei/cstr_functional_ontology_synethic_08242022.csv") 
dataFei <- read.csv("/Users/fchen1/OneDrive - Bayer/Codes/Rscripts/BAYER/DATA/Fei/cstr_functional_ontology_synethic_08242022.csv") 
par(mfrow=c(3,2))
plot(dataFei$concentrationA, type = "l", main = "Concentration of A");grid();abline(v=seq(0,5000,by=50)); 
plot(dataFei$Temp, type = "l", main = "Reactor Temperature");grid();abline(v=seq(0,5000,by=50))
plot(dataFei$coolingTemp, type = "l", main = "Cooling Temperature");grid();abline(v=seq(0,5000,by=50))
plot(dataFei$Temp_inlet, type = "l", main = "Inlet Temperature");grid();abline(v=seq(0,5000,by=50))
lines(smooth.spline(dataFei$Temp_inlet, spar = 0.2), col = "red", lwd=2)
 
plot(dataFei$flowRate, type = "l", main = "Flow Rate");grid();abline(v=seq(0,5000,by=50))
lines(smooth.spline(dataFei$flowRate, spar = 0.2), col = "red", lwd = 2)
plot(dataFei$concentrationA_inlet, type = "l", main = "Inlet Concentration of A");grid();abline(v=seq(0,5000,by=50))
lines(smooth.spline(dataFei$concentrationA_inlet, spar = 0.2), col = "red", lwd = 2)

z <- dataFei
z$coolingTemp <- z$coolingTemp + runif(5001,-10,10)
z$Group <- cut(1:5001,100,labels = FALSE)

z1 <- split(z, f=z$Group)
#i <- z1[[1]]

z_c <- lapply(z1, function(i){
  d2 <- i %>% dplyr::select(coolingTemp:Temp) %>%
    cor()
  d2 <- d2[upper.tri(d2)]
  return(d2)
}) %>%
  bind_rows() %>% t()

par(mfrow=c(1,1))
z_d <- dist(z_c)
zz <- cmdscale(z_d,k=2)
plot(zz, xlim=c(-1,1),ylim=c(-1,1));grid(lwd=2)
#points(zz[80:90,1],zz[80:90,2], col = "red", pch=16)
#points(zz[90:100,1],zz[90:100,2], col = "red", pch=16)
points(zz[60:90,1],zz[60:90,2], col = "red", pch=16)

g_all <- getMLEandLoglike(t(z_c))
g_red <- getMLEandLoglike(t(z_c[60:90,]))
g_white <- getMLEandLoglike(t(z_c[-c(60:90),]))

z_c <- rbind(z_c,
             g_all$mleTree %>% t(),
             g_red$mleTree %>% t(),
             g_white$mleTree %>% t())

z_d <- dist(z_c)
zz <- cmdscale(z_d,k=2)
par(mfrow=c(1,1))
plot(zz[,1],zz[,2], xlim=c(-1,1),ylim=c(-1,1), type = "n");grid(lwd=2)
text(zz[,1],zz[,2], labels = as.character(1:100), cex = 0.75)
#points(zz[80:90,1],zz[80:90,2], col = "red", pch=16)
#points(zz[90:100,1],zz[90:100,2], col = "red", pch=16)
#points(zz[60:90,1],zz[60:90,2], col = "red", pch=16)
points(zz[101,1],zz[101,2], col = "blue", pch=16, cex = 2)
points(zz[102,1],zz[102,2], col = "blue", pch=16, cex = 2)
points(zz[103,1],zz[103,2], col = "blue", pch=16, cex = 2)
 

```

```{r Synthetic Data Demonstration}

dat_corr <- dataFei %>%
  dplyr::select(coolingTemp:Temp) %>%
  cor()

round(dat_corr,3)


dat_corr_v <- dat_corr[upper.tri(dat_corr)] 
round(dat_corr_v,3)



data_corr_z <- z_trans(dat_corr_v)
round(data_corr_z,3)

################################################
################################################
par(mfrow=c(2,1))
x <- data_corr_z   ### x is a graph!
sd <- sqrt(1/(5001-3))
x.mat <- x
for(i in 2:100){
  x.mat <- rbind(x.mat, rnorm(15,x,sd=sd)) ### we are generating a new graph in this line
}                 ### x.mat is a population of graphs sampled from the dist of the first x.mat


x.cmd <- cmdscale(dist(x.mat), k=1) %>% as.data.frame()
x.cmd$Rank <- rank(x.cmd)

cbind(1:nrow(x.cmd), round(x.cmd$V1,2))
cbind(1:nrow(x.cmd),x.cmd$Rank)
par(mfrow=c(1,1))
plot(1:nrow(x.cmd), x.cmd$Rank, type = "step"); grid(lwd=2)
#text(1:nrow(x.cmd), x.cmd$Rank, x.cmd$Rank)

for(i in 1:10){
  x.mat <- rbind(x.mat, rnorm(15,x + runif(15,0,i*(.02)),2*sd)) ### we are generating a new graph in this line
}                 ### x.mat is a population of graphs sampled from the dist of the first x.mat

x.cmd <- cmdscale(dist(x.mat), k=1) %>% as.data.frame()
x.cmd$Rank <- rank(x.cmd)
cbind(1:nrow(x.cmd), x.cmd$Rank)

plot(1:nrow(x.cmd), x.cmd$Rank, type = "step"); grid(lwd=2)
#text(1:nrow(x.cmd), x.cmd$Rank, x.cmd$Rank)

par(mfrow=c(1,1))
qcc::qcc(x.cmd$Rank[1:100], type = "xbar.one")
qcc::qcc(x.cmd$Rank, type = "xbar.one")
###################################


```

```{r Real Data}


par(mfrow=c(3,2))
plot(dataFei$concentrationA, type = "l", main = "Concentration of A");grid();#abline(v=seq(0,5000,by=50)); 
plot(dataFei$Temp, type = "l", main = "Reactor Temperature");grid();#abline(v=seq(0,5000,by=50))

plot(dataFei$coolingTemp, type = "l", main = "Cooling Temperature");grid();#abline(v=seq(0,5000,by=50))
plot(dataFei$Temp_inlet, type = "l", main = "Inlet Temperature");grid();#abline(v=seq(0,5000,by=50))
lines(smooth.spline(dataFei$Temp_inlet, spar = 0.2), col = "red", lwd=2)

plot(dataFei$flowRate, type = "l", main = "Flow Rate");grid();#abline(v=seq(0,5000,by=50))
lines(smooth.spline(dataFei$flowRate, spar = 0.2), col = "red", lwd = 2)
plot(dataFei$concentrationA_inlet, type = "l", main = "Inlet Concentration of A");grid();#abline(v=seq(0,5000,by=50))
lines(smooth.spline(dataFei$concentrationA_inlet, spar = 0.2), col = "red", lwd = 2)



z <- dataFei
z$coolingTemp <- z$coolingTemp + runif(5001,-10,10)
z$Group <- cut(1:5001,100,labels = FALSE)

z1 <- split(z, f=z$Group)
#i <- z1[[1]]

cor_mats <- lapply(z1, function(i){
  d2 <- i %>%
    dplyr::select(coolingTemp:Temp) %>%
    cor()
})


z_c <- lapply(z1, function(i){
  d2 <- i %>%
    select(coolingTemp:Temp) %>%
    cor()
  d2 <- d2[upper.tri(d2)]
  return(d2)
}) %>%
  bind_rows() %>% t()


head(z_c)

par(mfrow=c(1,1))
f <- cmdscale(dist(z_c),k=1) %>% as.data.frame()
f$Index <- 1:nrow(f)
f$Rank <- rank(f$V1)
plot(1:nrow(f), f$Rank, type = "step")
q <- qcc::qcc(f$Rank[1:40], type = "xbar.one", newdata = f$Rank[41:100])

violations <- c(q$violations$beyond.limits, q$violations$violating.runs)
non_violations <- setdiff(c(1:100), violations)
wilcox.test(violations, non_violations)

```


```{r plotly}

library(plotly)
mds_plot <- plot_ly(f,  y=~Rank, type = "scatter", mode="lines")

corrs <- z_c %>% as.data.frame()
corrs$Index <- 1:nrow(corrs)
corr_plot <- plot_ly(corrs, y = ~V15, type = "scatter", mode = "lines") + add_lines(corr_plot, x = ~Index, y=~V1)

corr_plot <- corrs %>%
  plot_ly(x = ~Index, y=~V15, type = "scatter", mode = "lines", name = "Con_A:Temp") %>%
  add_trace(y= ~V1, inherit = TRUE, name = "Con_A_In:Tc")


# largeplot %>%
#   as.data.frame() %>%
#   plot_ly(x = ~Pos, y = ~RR, type = "scatter", mode = "lines", name = "RR") %>%
#   add_trace(y = ~HR, inherit = TRUE, name = "HR") %>%
#   add_trace(y = ~PULSE, inherit = TRUE, name = "PULSE", line = list(dash = "dash")) %>%
#   add_trace(y = ~SPo2, inherit = TRUE, name = "SPo2") %>%
#   rangeslider()



subplot(mds_plot, corr_plot, nrows = 2)

```








